name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'
    
      - name: install dependencies
        run: npm ci
        
      - name: build astro
        run: npm run build --if-present

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      
